---
title: "Enunciado de los problemas"
author: "María Vázquez de la Torre Becerra"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setupEnunMaria, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Teoría de la Decisión bajo Incertidumbre

En el siguiente documento vamos a enunciar los problemas inventados por cada miembro del grupo.

#### Problema 1 (María Vázquez de la Torre Becerra) \newline


María y Daniel están buscando una hacienda para celebrar su boda, su mayor ilusión es celebrarla al aire libre, pero no saben si el día de su boda lloverá o no. Están en duda con tres Haciendas que les ofrecen las siguientes condiciones:

-   "Hacienda Don Quijote": Esta hacienda es amplia y ofrece un espacio muy bonito para la boda al aire libre. El costo de alquiler de la hacienda es de 2000 euros en el exterior. El catering que proporciona la hacienda es de 150 euros por persona con la barra libre incluida durante las horas que los novio quieran. Si llueve tendría un coste adicional de 500 euros para montar el salón interior.

-   "Hacienda Rinconete y Cortadillo": Esta hacienda tiene un amplio interior. El alquiler del salón interior es de 2500 euros, pero si quieren celebrarlo en la parte exterior el alquiler sería de 4000. El catering que proporciona la hacienda es de 120 euros por persona y la barra libre tiene un costo de 150 euros la hora.

-   "Hacienda La Celestina": Esta hacienda sólo tiene opción de celebrarla en el exterior con un coste de alquiler de 500 euros, pero si llueve tiene un coste adicional de 3000 euros para montar una carpa resistente en el exterior. El catering que proporciona la hacienda es de 125 euros por persona y la barra libre tiene un costo de 350 euros por 4 horas y cada hora adicional que quieran añadir los novios a la barra libre sería de 165 euros la hora.

Si María Y Daniel tienen 300 invitados a la boda y quieren 7 horas de barra libre. ¿Que hacienda deberían escoger para minimizar el costo?

